apiVersion: apps/v1
kind: Deployment
metadata:
  name: listmonk-deployment
spec:
  replicas: 1
  template:
    spec:
      initContainers:
        - image: listmonk/listmonk:latest
          name: install
          command:
            - /bin/sh
            - -c
            - |
              ./listmonk --install --config /listmonk/config.toml --idempotent --yes
          # envFrom:
          #   - secretRef:
          #       name: listmonk-secrets
          volumeMounts:
            - name: config
              mountPath: /listmonk/config.toml
              subPath: config.toml
              # securityContext:
              #   runAsNonRoot: true
              #   runAsUser: 1900
              #   capabilities:
              #     drop:
              #       - ALL
              #   allowPrivilegeEscalation: false
              #   seccompProfile:
              #     type: RuntimeDefault

      containers:
        - name: listmonk
          env:
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: config
              mountPath: /etc/listmonk/config.toml
              subPath: config.toml
              # securityContext:
              #   runAsNonRoot: true
              #   runAsUser: 1900
              #   capabilities:
              #     drop:
              #       - ALL
              #   allowPrivilegeEscalation: false
              #   seccompProfile:
              #     type: RuntimeDefault
      volumes:
        - name: config
          configMap:
            name: app-config
      # volumes:
      #   - name: postgres-pv-claim
      #     persistentVolumeClaim:
      #       claimName: listmonk-pvc

