version: '3.9'

services:
  voidbox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voidbox
    ports:
      - '3001:3001'
    networks:
      - voidbox_network

networks:
  voidbox_network:
    external: true
