version: '3.9'

services:
  voidbox:
    # image: loneexile/blog:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voidbox
    restart: always
    ports:
      - '3001:3001'
    env_file:
      - .env
    networks:
      - voidbox_network
    depends_on:
      - voidsync
      - remark

  remark:
    image: umputun/remark42:latest
    container_name: 'remark42'
    hostname: 'remark42'
    restart: always
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    # uncomment to expose directly (no proxy)
    ports:
      - '8080:8080'
      # - '443:8443'
    env_file:
      - .env
    volumes:
      - ./var:/srv/var

  note_app:
    image: loneexile/note_app:latest
    container_name: note_app
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    networks:
      - voidbox_network
    depends_on:
      - voidsync

  voidsync:
    image: loneexile/voidsync:latest
    container_name: voidsync
    restart: always
    ports:
      - '8090:8090'
    env_file:
      - .env
    depends_on:
      - minio
      - surrealdb
    networks:
      - voidbox_network

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - '9090:9090'
    env_file:
      - .env
    volumes:
      - ${HOME}/voidsync/minio:/data
    command: server /data --console-address ":9090"
    networks:
      - voidbox_network

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: always
    volumes:
      - ${HOME}/voidsync/surrealdb:/mydata
    command: start --log trace --user root --pass root file:/mydata/mydatabase.db
    networks:
      - voidbox_network

networks:
  voidbox_network:
    name: voidbox_network
