version: '3.9'

services:
  voidbox:
    image: loneexile/blog:latest
    container_name: voidbox
    ports:
      - '3001:3001'
    restart: always
    networks:
      - voidbox_network

networks:
  voidbox_network:
    external: true
