/** @type {import('tailwindcss').Config} */
const colors = require("tailwindcss/colors");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}",
    "./node_modules/flowbite/**/*.js",
  ],
  plugins: [require("flowbite-typography"), require("flowbite/plugin")],
  darkMode: "class",
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      slate: colors.slate,
      stone: colors.stone,
      blue: colors.blue,
      rose: colors.rose,
      green: colors.green,
      black: colors.black,
      white: colors.white,
      gray: colors.gray,
      emerald: colors.emerald,
      indigo: colors.indigo,
      yellow: colors.yellow,
    },
    extend: {
      colors: {
        text: {
          50: "#f7eef0",
          100: "#eedde0",
          200: "#debac2",
          300: "#cd98a3",
          400: "#bd7585",
          500: "#ac5366",
          600: "#8a4252",
          700: "#67323d",
          800: "#452129",
          900: "#221114",
          950: "#11080a",
        },
        background: {
          50: "#f9ecef",
          100: "#f2d9df",
          200: "#e6b3bf",
          300: "#d98c9f",
          400: "#cc667f",
          500: "#bf4060",
          600: "#99334c",
          700: "#732639",
          800: "#4d1926",
          900: "#260d13",
          950: "#13060a",
        },
        primary: {
          50: "#fde8ed",
          100: "#fbd0db",
          200: "#f6a2b7",
          300: "#f27393",
          400: "#ee446f",
          500: "#e9164b",
          600: "#bb113c",
          700: "#8c0d2d",
          800: "#5d091e",
          900: "#2f040f",
          950: "#170207",
        },
        secondary: {
          50: "#fce8ed",
          100: "#fad1db",
          200: "#f4a4b8",
          300: "#ef7694",
          400: "#ea4871",
          500: "#e41b4d",
          600: "#b7153e",
          700: "#89102e",
          800: "#5b0b1f",
          900: "#2e050f",
          950: "#170308",
        },
        accent: {
          50: "#fee6ec",
          100: "#fecdd9",
          200: "#fc9cb4",
          300: "#fb6a8e",
          400: "#fa3869",
          500: "#f90643",
          600: "#c70536",
          700: "#950428",
          800: "#63031b",
          900: "#32010d",
          950: "#190107",
        },
      },
      animation: {
        "skew-scroll": "skew-scroll 20s linear infinite",
      },
      keyframes: {
        "skew-scroll": {
          "0%": {
            transform:
              "rotatex(20deg) rotateZ(-20deg) skewX(20deg) translateZ(0) translateY(0)",
          },
          "100%": {
            transform:
              "rotatex(20deg) rotateZ(-20deg) skewX(20deg) translateZ(0) translateY(-100%)",
          },
        },
      },
      typography: ({ theme }) => ({
        rose: {
          css: {
            "--tw-prose-body": theme("colors.rose[500]"),
            "--tw-prose-headings": theme("colors.rose[900]"),
            "--tw-prose-lead": theme("colors.rose[500]"),
            "--tw-prose-links": theme("colors.rose[600]"),
            "--tw-prose-bold": theme("colors.rose[900]"),
            "--tw-prose-counters": theme("colors.rose[500]"),
            "--tw-prose-bullets": theme("colors.rose[500]"),
            "--tw-prose-hr": theme("colors.rose[200]"),
            "--tw-prose-quotes": theme("colors.rose[900]"),
            "--tw-prose-quote-borders": theme("colors.rose[300]"),
            "--tw-prose-captions": theme("colors.rose[700]"),
            "--tw-prose-code": theme("colors.rose[900]"),
            "--tw-prose-code-bg": theme("colors.rose[50]"),
            "--tw-prose-pre-code": theme("colors.rose[100]"),
            "--tw-prose-pre-bg": theme("colors.rose[900]"),
            "--tw-prose-th-borders": theme("colors.rose[300]"),
            "--tw-prose-td-borders": theme("colors.rose[200]"),
            "--tw-format-th-bg": theme("colors.rose[50]"),
            "--tw-prose-invert-body": theme("colors.rose[200]"),
            "--tw-prose-invert-headings": theme("colors.white"),
            "--tw-prose-invert-lead": theme("colors.rose[300]"),
            "--tw-prose-invert-links": theme("colors.white"),
            "--tw-prose-invert-bold": theme("colors.white"),
            "--tw-prose-invert-counters": theme("colors.rose[400]"),
            "--tw-prose-invert-bullets": theme("colors.rose[600]"),
            "--tw-prose-invert-hr": theme("colors.rose[700]"),
            "--tw-prose-invert-quotes": theme("colors.pink[100]"),
            "--tw-prose-invert-quote-borders": theme("colors.rose[700]"),
            "--tw-prose-invert-captions": theme("colors.rose[400]"),
            "--tw-prose-invert-code": theme("colors.white"),
            "--tw-prose-invert-pre-code": theme("colors.rose[300]"),
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": theme("colors.rose[600]"),
            "--tw-prose-invert-td-borders": theme("colors.rose[700]"),
            "--tw-format-invert-th-bg": theme("colors.rose[700]"),
          },
        },
      }),
    },
    fontFamily: {
      body: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      sans: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
    },
  },
};
