apiVersion: v1
kind: Service
metadata:
  name: listmonk-service
  labels:
    app: listmonk
spec:
  selector:
    app: listmonk
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
