apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - name: http
      protocol: TCP
      port: 9432
      targetPort: 5432
