apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db-statefulset.yaml
  - db-service.yaml
  # - pv.yaml
  - pvc.yaml
  - app-service.yaml
  - app-deployment.yaml

generatorOptions:
  labels:
    app: listmonk-stack
  disableNameSuffixHash: true

configMapGenerator:
  - name: app-config
    files:
      - files/config.toml

secretGenerator:
  - name: postgres-secret
    envs:
      - files/.env


