apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

generatorOptions:
  labels:
    app: listmonk-handle
  disableNameSuffixHash: true

secretGenerator:
  - name: listmonk-api
    envs:
      - files/.env


