apiVersion: v1
kind: Service
metadata:
  name: blog-service
  labels:
    app: blog
spec:
  selector:
    app: blog
  ports:
    - protocol: TCP
      port: 4321
      targetPort: 4321
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  labels:
    app: blog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: loneexile/blog:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4321

