version: '3.9'
services:
  # voidbox:
  #   image: loneexile/blog:latest
  #   container_name: voidbox
  #   restart: always
  #   ports:
  #     - '4321:4321'
  #   env_file:
  #     - .env
  #   networks:
  #     - voidbox_network
  #   depends_on:
  #     - remark
  remark:
    image: umputun/remark42:latest
    container_name: 'remark42'
    hostname: 'remark42'
    restart: always
    # network_mode: bridge
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    # uncomment to expose directly (no proxy)
    ports:
      - '8080:8080'
      # - '443:8443'
    env_file:
      - .env
    volumes:
      - ./var:/srv/var
      - ./customised_templates/email_confirmation_login.html.tmpl:/srv/email_confirmation_login.html.tmpl:ro
      - ./customised_templates/email_confirmation_subscription.html.tmpl:/srv/email_confirmation_subscription.html.tmpl:ro
      - ./customised_templates/email_reply.html.tmpl:/srv/email_reply.html.tmpl:ro
      - ./customised_templates/email_unsubscribe.html.tmpl:/srv/email_unsubscribe.html.tmpl:ro
      - ./customised_templates/error_response.html.tmpl:/srv/error_response.html.tmpl:ro

# networks:
#   voidbox_network:
#     name: voidbox_network
