apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: db-statefulset.yaml
  # - path: pv.yaml
  - path: pvc.yaml
  - path: app-deployment.yaml

