apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-statefulset
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: postgresql
      volumes:
        - name: postgres-pv-claim
          persistentVolumeClaim:
            claimName: listmonk-db-pvc

