apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-statefulset
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: postgresql
          resources:
            requests:
              cpu: "100m"
              memory: "25Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: TIME_ZONE
              value: "Asia/Bangkok"
          volumeMounts:
            - name: postgres-pv-claim
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-pv-claim
          persistentVolumeClaim:
            claimName: postgresql-pvc

